sudo: required
services:
  - docker

before_install:
  - find Gemfile* -type f | xargs touch -t 7805200000
  - docker build -t travis/docker-react -f Dockerfile.dev .

scripts:
  - docker run travis/docker-react:latest npm run test -- --coverage